### ISSUE TITLE
Support for other RDBMS?

### ISSUE THREAD

**Issue by t-oster** [adelsz/pgtyped#1]
Hi, your project looks as if you had the same idea as myself with LazySQL (https://lazysql.thomas-oster.de) but with typescript instead of java.
However will your project support other RDBMS than Postgres in the future?

**Comment by adelsz** [comment]
Hi @t-oster, LazySQL looks nice! Happy to see other libraries focusing on strictly typed raw SQL.
PgTyped is mostly focused on Postgres DB at the moment. Additional database support might be coming in the future, depending on demand.
