### ISSUE TITLE
[Idea] Generate runtime types with io-ts

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#100]
I have been enjoying 'database-first domain modelling', and also `io-ts` (having come across it here) (thanks).

Thinking about higher-order types, custom types, and type overrides #60 at the same time as defining io-ts schema has made me wonder if io-ts should generate _runtime_ types (rather than static types) using io-ts. It would be strictly more powerful and not much more effort from the code generation side (actually it might be _easier_ https://github.com/gcanti/io-ts-codegen).

You can still get hold of types by using `t.TypeOf<typeof IoTsSchema>` so we can just put that everywhere we'd currently put our existing types.

This allows dependees not only to check their code for type agreement but also to parse inputs that are related to database-defined schema (as they surely must be). This could allow the DB schema to be the statically typed centre of a system. Inputs can be typed at run-time and compile-time from schema derived from the DB.

I think `io-ts` will be much better than the inchoate type system I added for enums for transporting type information around for composite types. And I can't entirely put my finger on why yet, but I think using runtime types at generation time and in generated code (as well as to carry the database type mapping) is going to unlock some powerful features.

**Comment by adelsz** [comment]
Closing as stale. Runtime type validation is a non-goal.
