### ISSUE TITLE
Support converting column names to camelCase

### ISSUE THREAD

**Issue by darky** [adelsz/pgtyped#107]
We in our project use implicit conversion of snake_case -> camelCase fields of database result in runtime. 
Is exists ability to represent it via **pgtyped** ?

```ts
export interface IFindBookByIdResult {
  id: number;
  author_id: number | null; // <-- snake_case field
}
```

↓ ↓ ↓

```ts
export interface IFindBookByIdResult {
  id: number;
  authorId: number | null; // <-- camelCase field
}
```

**Comment by adelsz** [comment]
Fixed in #110.

**Comment by danielbrauer** [comment]
I've just enabled this in my project, but it appears to only change the types rather than the actual query results. I just want to double-check that this is intended, and I should use something like https://www.npmjs.com/package/pg-camelcase to change the data at runtime?

**Comment by adelsz** [comment]
Yes, this is why it isn't documented anywhere. pgTyped will be able to do that once the runtime layer is complete.
Meanwhile something like pg-camelcase should work.
