### ISSUE TITLE
[IDEA] Support raw (unescaped) SQL to be passed to queries

### ISSUE THREAD

**Issue by mmiszy** [adelsz/pgtyped#111]
I have a query written in SQL and I love that the types are automatically created. So far, so good :)

# The problem:
However, my use case requires that I dynamically generate `ORDER BY …` phrase and unfortunately that's not possible with parametrised queries.

# Solution:
Therefore, I need to pass a raw SQL code to the query which would be concatenated with it as is, without any escaping.

# Proposed syntax:
Same as with usual parameters, but their names would be prefixed with `unsafe_`:

`ORDER BY :unsafe_orderBy`

Additionally, and also to make sure it's a non-breaking change, it could be indicated when the query is used:

```ts
import { unsafe } from 'pg-typed';
// …
await myQuery.run({ unsafe_orderBy: unsafe(`"MyColumn" ASC`) };
```

# Risks:
When used incorrectly, this could lead to SQLi vulnerabilities.

**Comment by adelsz** [comment]
@mmiszy You can do sorting by custom column like this:
```sql
/* A query to get all comments */
/* @name GetAllComments */
SELECT * FROM book_comments WHERE id = :id ORDER BY :order_column;
```
If you need a dynamic sort column and order:
```sql
/* A query to get all comments */
/* @name GetAllComments */
SELECT * FROM users ORDER BY (CASE WHEN :asc = true then :sort_column end) asc, :sort_column desc;
```
PgTyped infers the above query to take two params: `asc: boolean` and `sort_column:string`.

As for unsafe parameters:
We do plan on adding custom interpolations and partial queries in the future, but they are still at design stage, it is hard to do them in a typesafe way.

**Comment by redinggg** [comment]
> @mmiszy You can do sorting by custom column like this:
> 
> ```sql
> /* A query to get all comments */
> /* @name GetAllComments */
> SELECT * FROM book_comments WHERE id = :id ORDER BY :order_column;
> ```
> 
> If you need a dynamic sort column and order:
> 
> ```sql
> /* A query to get all comments */
> /* @name GetAllComments */
> SELECT * FROM users ORDER BY (CASE WHEN :asc = true then :sort_column end) asc, :sort_column desc;
> ```
> 
> PgTyped infers the above query to take two params: `asc: boolean` and `sort_column:string`.
> 
> As for unsafe parameters:
> We do plan on adding custom interpolations and partial queries in the future, but they are still at design stage, it is hard to do them in a typesafe way.

does not work ;(
I am trying to do this:
```sql
SELECT * FROM posts ORDER BY (CASE WHEN :asc = true then :sort_column end) asc, :sort_column desc;
```

```javascript
const params = {
  asc: false,
  sort_column: 'id'
}
const posts = await getPosts.run(params, client)
```

As a result, nothing sorts
Everything remains the same
