### ISSUE TITLE
PG JSON unions are unsupported

### ISSUE THREAD

**Issue by steelbrain** [adelsz/pgtyped#113]
```
Update "Table" set params = "params" || :params where "id" = :id;
```

breaks PGTyped. This is valid PG syntax, for example, try running this in REPL

```
select '{"a" :"a", "b": "b"}'::jsonb || '{"a": "b"}'::jsonb as text
```

**Comment by adelsz** [comment]
Hm, running `UPDATE notifications SET payload = '{"a": "b"}'::jsonb || $params WHERE id = $id;` works for me, with `params` being inferred to be JSON by pgTyped.
Can you attach the actual query you are trying to execute?

**Comment by steelbrain** [comment]
Unable to repro in latest release
