### ISSUE TITLE
count field filled with string at runtime, even though type is number

### ISSUE THREAD

**Issue by danielbrauer** [adelsz/pgtyped#117]
I've got a query defined like this:

`/* @name CountByName */
SELECT COUNT(*) FROM users WHERE username = :username;
`

But at runtime it's returning `[{count:"0"}]`.

What might I be doing wrong?

**Comment by adelsz** [comment]
In PG SQL queries count is returned as `bigint`.
PG's `bigint` can be bigger than JS's `Number.MAX_SAFE_INTEGER` so it is parsed as string by `node-postgres`.
If you are sure that your counts will fit into `int4` then a potential workaround is to typecast the count to `int` in your query:
```
SELECT COUNT(*)::int FROM users WHERE username = :username; 
```

**Comment by danielbrauer** [comment]
That makes sense, thank you! Would it make sense to do something like this? https://github.com/brianc/node-pg-types/issues/78

**Comment by danielbrauer** [comment]
Also, is it a bug that the type is number if it ends up being string at runtime?

**Comment by adelsz** [comment]
> That makes sense, thank you! Would it make sense to do something like this? [brianc/node-pg-types#78](https://github.com/brianc/node-pg-types/issues/78)


Yes it makes sense, but currently we do not offer a way to override pgTyped's default type maps if you decide to use custom type parsers with `node-postgres`.
We plan to provide automatic `BigInt` conversion once we integrate with `node-postgres` more tightly.

> Also, is it a bug that the type is number if it ends up being string at runtime?

Yes, please open an issue if that happened. Might be a mapping mistake somewhere in our type map config.

**Comment by danielbrauer** [comment]
> Yes, please open an issue if that happened. Might be a mapping mistake somewhere in our type map config.

Ah, that was the original reason for this issue. I was checking whether `count === 0` and it didn't because it was a string.

**Comment by adelsz** [comment]
If I understood you correctly casting `COUNT(*)::int` worked for you.
Closing this issue, let me know that is not the case.
