### ISSUE TITLE
not-null columns in insert queries

### ISSUE THREAD

**Issue by Maxpain177** [adelsz/pgtyped#118]
Hello. Thank you for this awesome project.

We have table `items` with field `name`, which is not nullable.
We also have query:
```sql
INSERT INTO items (name)
VALUES (name)
```

Generated type:
```
export interface ICreateItemParams {
  name: string | null | void;
}
```

Why it has `null` and `void` types?

**Comment by Maxpain177** [comment]
@adelsz

**Comment by adelsz** [comment]
Unfortunately, Postgres doesn't provide nullability information on parameter types, so we have to assume all parameters to be nullable by default.

**Comment by Maxpain177** [comment]
> Unfortunately, Postgres doesn't provide nullability information on parameter types

Hi @adamochayon. Are you sure?

**Comment by adelsz** [comment]
Yes, Postgres only returns type OIDs for parameters. The `pg_type` table doesn't provide any nullability info on them.

**Comment by Maxpain177** [comment]
@adelsz Maybe we can get this information from table's fields definitions?

**Comment by adelsz** [comment]
@Maxpain177 Unfortunately not, there is no exposed way of inferring table columns from params.

**Comment by chmln** [comment]
@adelsz Couldn't we extract nullable types from `information_schema` ?

![image](https://user-images.githubusercontent.com/11352152/90326814-e0d00000-df5a-11ea-8900-f4108ae4887d.png)

**Comment by adelsz** [comment]
@chmln To relate parameters back to their column definition we would need to build a complete SQL engine, which is not feasible at the moment.
Maybe we can add some heuristics for simple insert queries to partially solve this, but that is about it.

**Comment by jgonera** [comment]
@adelsz I know this is closed but I think supporting this for simple inserts and updates would be a great feature. I think in many projects most inserts and updates fall into this category. https://jawj.github.io/zapatos/#typescript-schema does something like this by generating its `Insertable` and `Updatable` types.
