### ISSUE TITLE
Wrong nullability of columns, which calculated from functions

### ISSUE THREAD

**Issue by darky** [adelsz/pgtyped#120]
Few examples:

```sql
select sum(column) * 12 as hour ...
```

```sql
select to_char(column, 'DD.MM.YYYY HH24:MI') as date ...
```

In this examples `column` is nullable, which generate `hour` and `date` nullable too at runtime.
But **pgtyped** generate not null type of column.

**Comment by adelsz** [comment]
Looks like postgres fails to provide nullability data for such columns.
I have opened a bug to always generate nullable types for fields without nullability information: #121. 
Closing this one, as it is a subset of that bigger task.
