### ISSUE TITLE
Columns without attribute data should be nullable

### ISSUE THREAD

**Issue by adelsz** [adelsz/pgtyped#121]
Looks like Postgres doesn't provide `pg_attribute` information for aggregated/derived columns (ex. #120).
Example: `select sum(column) * 12 as hour ...`

We need to make sure we generate nullable types for all such columns, even if their non-nullable (postgres doesn't provide that info).

**Comment by darky** [comment]
Can be closed! Should be fixed after `0.8.1`

**Comment by darky** [comment]
@adelsz can you please bump new version in npm (at least in beta channel)

**Comment by adelsz** [comment]
Thanks for the PR @darky!
Fixed in `0.8.2`.
