### ISSUE TITLE
Feasibility of Generic Drivers for other databases (SQLite)

### ISSUE THREAD

**Issue by Taytay** [adelsz/pgtyped#124]
First, thank you for this project! 

I saw that there are folks that desire this for MySQL (#50), and this is a related request. I am considering trying to hack in support for SQLite, and wanted to talk about feasibility.

We currently use Typescript to build and run queries against a SQLite database (https://github.com/sql-js/sql.js). I am of course curious how easy it would be to write a "driver" that I could substitute for the default PG driver you have implemented.

I took a look at the generator:
https://github.com/adelsz/pgtyped/blob/1ec837cb1311bff843b2c1091edd506217a5b9ff/packages/cli/src/generator.ts#L64

At present, it looks like the `getTypes` function, as implemented here, is the one doing the talking to PG: https://github.com/adelsz/pgtyped/blob/963221952b14efc2080f2c8098cc29578bb6bb9c/packages/query/src/actions.ts#L250-L254

Once getTypes returns its `IQueryTypes`, however, the generator appears to be unaware of PG, right?

I realize that there might be work involved in making the driver selectable, etc, and creating the appropriate connection instead of assuming it's an AsyncQueue, but that looks pretty do-able. https://github.com/adelsz/pgtyped/blob/e84eb080c10cce94e810d66e41985f0fd93b8a5c/packages/cli/src/index.ts#L124

Before I get cracking on this, would I be in thinking that a new DB driver should focus on implementing `getTypes` for SQLite, and that the rest of the "knowledge" and assumptions of PG would be relatively simple to extract out of the generator?

**Comment by adelsz** [comment]
Thanks @Taytay!

pgTyped relies on the DB engine to provide a way to infer and extract type information from a query.
Such a DB engine when provided with a `SELECT id, name, age FROM users WHERE id = $1` query, should allow pgTyped to get the types for returned rows  `(id = uuid, name = text, age = int)` and for used parameters `$1 = uuid`.

PostgreSQL provides this at protocol level through prepared statements.
I am not very familiar with SQLite, so I am not sure if it provides a method to get query type information through their API?
Is that even possible given the "manifest typing" features of sqlite?

**Comment by Taytay** [comment]
That's a really good point @adelsz  - I was looking at another aspect of the SQLite API and thought that I could get the types, but I didn't realize it changed on a row by row basis! I might have to try a different approach that still relies upon parsing the query, but is able to map columns to the schema more directly somehow. 

SQLite aside, do you think my approach I outlined above (in particular where I'd look to change code or add a driver) would work?

**Comment by Taytay** [comment]
You are free to close this out BTW.
