### ISSUE TITLE
Annotation ideas: @single and @maybe

### ISSUE THREAD

**Issue by meoyawn** [adelsz/pgtyped#128]
`@single`: returns exactly one row. Not nullable
`@maybe`: returns zero or one rows. Nullable

I'm just starting to use pgtyped, maybe having an array everywhere is most optimal in practice

**Comment by adelsz** [comment]
This is will be useful, slonik does something similar.
To add this we will need to complete the new runtime layer first, so it is currently blocked by that.

**Comment by adelsz** [comment]
I know this is old, but I am now confident that this can achieved both at run and compile time with a small custom wrapper around `query.run`. It is probably best if we keep this out of pgTyped to prevent bloat.
