### ISSUE TITLE
sql files not parsed when parameter type cannot be determined

### ISSUE THREAD

**Issue by mudrz** [adelsz/pgtyped#132]
when you have a table
```sql
CREATE TABLE untitled_table (
    id SERIAL PRIMARY KEY,
    a text,
    b text NOT NULL
);
```

the following query
```sql
/*
  @name UpdateA
*/
UPDATE public.untitled_table
SET
  a = (
    CASE WHEN (:a IS NOT NULL)
      THEN :a
      ELSE a
    END
  )
WHERE id = :id;
```
does not parse
```
Error in query. Details: {
  errorCode: 'scanner_yyerror',
  hint: undefined,
  message: 'syntax error at or near ":"',
  position: '57'
}
```

the same query in typescript files results in `could not determine data type of parameter $...`.
in typescript files casting the value via `::TEXT` fixes the issue

in sql files
```sql
UPDATE public.untitled_table
SET
  a = (
    CASE WHEN (:a::TEXT IS NOT NULL)
      THEN :a
      ELSE a
    END
  )
WHERE id = :id;
```
still results in a syntax error

**Comment by adelsz** [comment]
Are you sure you are using the latest version?
These queries seem to be working in:
https://github.com/adelsz/pgtyped/blob/b32f559b44f9708d98fe750550e5a342d8d94a53/packages/example/src/books/books.sql#L11-L22

**Comment by mudrz** [comment]
.. you are right, it seems that I didn't have the last version, just updated it and the query is parsed correctly

thank you
