### ISSUE TITLE
ending commas are not parsed correctly

### ISSUE THREAD

**Issue by mudrz** [adelsz/pgtyped#133]
when you have a table
```sql
CREATE TABLE untitled_table (
    id SERIAL PRIMARY KEY,
    a text,
    b text NOT NULL
);
```

a query like
```sql
/*
  @name UpdateA
*/
UPDATE public.untitled_table
SET
  a = :a,
  b = :b
WHERE id = :id;
```
results in a parse error: `Parse error: extraneous input 'a,' expecting ID`

you need to add a white space between the identifier and the comma for it to parse:
```sql
UPDATE public.untitled_table
SET
  a = :a ,
  b = :b
WHERE id = :id;
```

**Comment by adelsz** [comment]
Which version are you using?
This example has a comma and is working:
https://github.com/adelsz/pgtyped/blob/4960191f1addc921be1370fe5c6dcb82dbc7fc13/packages/example/src/books/books.sql#L11-L18

**Comment by mudrz** [comment]
just tested with the new version and it is working correctly, thank you
