### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by mudrz** [adelsz/pgtyped#134]
What is the status of the project?
Is it used in production anywhere?
Would you recommend using it in production?

**Comment by adelsz** [comment]
1. It is an active project.
2. There are a couple projects using it, but it is far from mainstream adoption.
3. Yes, but with caution until it hits version 1.0 because our APIs might change.

**Comment by mudrz** [comment]
@adelsz to clarify - are these business, user facing web applications, or hobby projects?

checking in advance if this is an appropriate solution since there are production tested alternatives (that are not as nice as pgtyped though)

**Comment by adelsz** [comment]
> to clarify - are these business, user facing web applications, or hobby projects?

I don't have the statistics unfortunately.

> checking in advance if this is an appropriate solution since there are production tested alternatives (that are not as nice as pgtyped though)

At runtime pgTyped is very lightweight in what it does, it is SQL with minor syntactic sugar and is mostly compile-time. This means it is easy to migrate your project away from it if you don't like it at some point. Using pure SQL for a prod project is ok if you understand what you are doing and take care to prevent common pitfalls like N + 1, etc..
