### ISSUE TITLE
@types/camel-case is deprecated

### ISSUE THREAD

**Issue by mudrz** [adelsz/pgtyped#135]
when installing pgtyped there is a warning:

> npm WARN deprecated @types/camel-case@1.2.1: This is a stub types definition for camel-case (https://github.com/blakeembrey/camel-case). camel-case provides its own type definitions, so you don't need @types/camel-case installed!

how can I remove this line, I see that there's a bot for dependencies?
https://github.com/adelsz/pgtyped/blob/52fc20ff59bcdf6a510a400dd3a71cf7657c7c4a/packages/cli/package.json#L28

**Comment by adelsz** [comment]
Yes, do it 👍
