### ISSUE TITLE
Type mismatch for INTERVAL

### ISSUE THREAD

**Issue by meoyawn** [adelsz/pgtyped#138]
pgtyped generates `string` type for `INTERVAL` values

But in runtime the value is `PostgresInterval` object

**Comment by silasdavis** [comment]
Sounds like you are probably using https://github.com/bendrucker/postgres-interval/blob/master/index.js#L5? The default for the node Postrgres module is a string.

Postgres also allows three different interval styles: https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-INTERVALSTYLE. Using something other than string here would break the others.

A solution to https://github.com/adelsz/pgtyped/issues/60 would probably allow us to address this.

**Comment by meoyawn** [comment]
yarn.lock:

```
pg@^8.3.0:
  version "8.3.0"
  resolved "https://registry.yarnpkg.com/pg/-/pg-8.3.0.tgz#941383300d38eef51ecb88a0188cec441ab64d81"
  integrity sha512-jQPKWHWxbI09s/Z9aUvoTbvGgoj98AU7FDCcQ7kdejupn/TcNpx56v2gaOTzXkzOajmOEJEdi9eTh9cA2RVAjQ==
  dependencies:
    buffer-writer "2.0.0"
    packet-reader "1.0.0"
    pg-connection-string "^2.3.0"
    pg-pool "^3.2.1"
    pg-protocol "^1.2.5"
    pg-types "^2.1.0"
    pgpass "1.x"
    semver "4.3.2"

pg-types@^2.1.0:
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/pg-types/-/pg-types-2.2.0.tgz#2d0250d636454f7cfa3b6ae0382fdfa8063254a3"
  integrity sha512-qTAAlrEsl8s4OiEQY69wDvcMIdQN6wdz5ojQiOy6YRMuynxenON0O5oCpJI6lshc6scgAY8qvJ2On/p+CXY0GA==
  dependencies:
    pg-int8 "1.0.1"
    postgres-array "~2.0.0"
    postgres-bytea "~1.0.0"
    postgres-date "~1.0.4"
    postgres-interval "^1.1.0"
```

I guess I just need to override default type parsers, will try https://github.com/brianc/node-pg-types

**Comment by meoyawn** [comment]
@silasdavis my problem is that I have a nullable `INTERVAL` column.

Selecting it as-is generates `string | null` but returns `PgInterval` in runtime
Selecting it as `column::TEXT` generates `string` but returns `string | null` in runtime

that's the current situation

**Comment by meoyawn** [comment]
```ts
import { types } from 'pg';

types.setTypeParser(types.builtins.INTERVAL, x => x)
```

fixes everything, respects nullability and `SET intervalstyle`

**Comment by adelsz** [comment]
Thanks @meoyawn!
This requires the runtime layer. Tracking this here #148
