### ISSUE TITLE
Type mismatch for LIMIT

### ISSUE THREAD

**Issue by meoyawn** [adelsz/pgtyped#139]
```sql
/* @name testing */
SELECT *
FROM expenses
LIMIT :limit;
```

generates

```ts
/** 'Testing' parameters type */
export interface ITestingParams {
  limit: string | null | void;
}
```

I'm not too sure, but it should probably be `limit: number`

**Comment by silasdavis** [comment]
This will be the same underlying issue as: https://github.com/adelsz/pgtyped/issues/117

**Comment by meoyawn** [comment]
@silasdavis thanks! I guess this could be solved with combination of https://github.com/adelsz/pgtyped/issues/60 and https://github.com/brianc/node-pg-types

**Comment by adelsz** [comment]
Thanks @meoyawn @silasdavis!
Tracking this here #145
