### ISSUE TITLE
CLI Problem parsing BEGIN; + COMMIT;

### ISSUE THREAD

**Issue by thiskevinwang** [adelsz/pgtyped#142]
# Description

It looks like there's an issue with PGTyped watchmode parsing `BEGIN;` + `COMMIT;`, as well as generating types correctly

### Example 1 - Working Case ✅ (but without BEGIN/COMMIT)

<details open>

query.sql

```sql
/* @name test */
SELECT
  *
FROM
  credits
WHERE
  id = :myInput;
```

... And generated param:

```ts
/** Types generated for queries found in "src/services/credit/credits.sql" */
import { PreparedQuery } from '@pgtyped/query';

/** 'Test' parameters type */
export interface ITestParams {
  myInput: string | null | void;
}

// truncated...
```

</details>

---

### Example 2 - CLI Error ❌ 

<details open>

query.sql
- added `BEGIN;` and `COMMIT;`
```sql
/* @name test */
BEGIN;

SELECT
  *
FROM
  credits
WHERE
  id = :myInput;

COMMIT;
```
...CLI error:
```bash
[0] Processing <REDACTED PATH TO FILE>
[0] Parsed file:
[0] 1 | /* @name test */
[0] 2 | BEGIN;
[0] 3 | 
[0] 4 > SELECT
[0] 5 |   *
[0] 6 | FROM
[0] 7 |   credits
[0] 8 | WHERE
[0] 9 |   id = :myInput;
[0] 10 | 
[0] 11 | COMMIT;
[0] Errors:
[0] - (4:0) Parse error: extraneous input 'SELECT' expecting {<EOF>, '/*'}
```

</details>

---

### Example 3 - Parsed successfully ✅ ; Invalid 🐬SQL + Incorrect 🟦TS types

<details open>

query.sql
- note the exact semicolons
- This is also invalid SQL

```sql
/* @name test */
BEGIN
SELECT
  *
FROM
  credits
WHERE
  id = :myInput COMMIT;
```

... And generated param:

```ts
/** Types generated for queries found in "src/services/credit/credits.sql" */
import { PreparedQuery } from '@pgtyped/query';

/** Query 'Test' is invalid, so its result is assigned type 'never' */
export type ITestResult = never;

/** Query 'Test' is invalid, so its parameters are assigned type 'never' */
export type ITestParams = never;
```

</details>

**Comment by adelsz** [comment]
Hi @thiskevinwang, 

pgTyped only supports **single statement** queries because type inference can only be done at single statement level in postgres. If you need multi-statement queries, then I recommend splitting them into multiple ones. Example:
```ts
function queryInTrx() {
  await client.query('BEGIN');
  await testQuery.run({id: 123}, client);
  await client.query('COMMIT');
}
```
