### ISSUE TITLE
Array type parsing

### ISSUE THREAD

**Issue by adelsz** [adelsz/pgtyped#144]
Add support for Postgres array parsing both at compile and runtime.
Solves #95

**Comment by golergka** [comment]
This blocks me in my work - I'd be glad to help if you gave me some pointers as to where and how to implement it.

**Comment by Maxpain177** [comment]
Same problem

**Comment by golergka** [comment]
One more example, now with function parameters

# Steps to reproduce

On my Postgresql server, I have function, defined like this:

```SQL
CREATE OR REPLACE FUNCTION function_name(
	_steam_ids integer[])
    RETURNS integer[]
```

In my Typescript, I define query:

```Typescript
const queryName = sql`
	-- ...
	some_function($$parameterName))
	-- ...
`

# Expected result

export interface IQueryNameParams {
  parameterName: Array<number | null | void>;
}

# Actual result

export interface IQueryNameParams {
  parameterName: Array<never | null | void>;
}
