### ISSUE TITLE
Array expansion without surrounding parens

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#150]
I want to write a query that looks like this, expanded:

```sql
UPDATE users AS u
SET unread_notifications_count = unread_notifications_count + n.count
FROM (VALUES (1, 1),(2, 2))
AS n(userID, count)
WHERE u.id = n.userID
```

The important thing here is the VALUES command: `VALUES (1,1), (2,2)` - as you can see, the array is not surrounded by parens, as it is when used in INSERT command.

Unfortunately, now the "array spread and pick" expansion type always surrounds the array in parens, so when I write this query in Typescript:

```typescript
const updateUnreadNotificationsCounts = sql`
	UPDATE users
	SET unread_notifications_count = unread_notifications_count + n.count
	FROM (VALUES $$notifications(userID, count))
	AS n(userID, count)
	WHERE users.id = n.userID
`
```

I get an error:

```
Error in query. Details: {
  errorCode: 'op_error',
  hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
  message: 'operator does not exist: integer = text',
  position: '146'
}
```

Because it expands no to the query above, but to this:

```sql
UPDATE users AS u
SET unread_notifications_count = unread_notifications_count + n.count
FROM (VALUES ((1, 1),(2, 2)))
AS n(userID, count)
WHERE u.id = n.userID
```

Notice extra set of parens in `VALUES ((1, 1),(2, 2))`.

Can I achieve the desired result with the current pgtyped, or is it a new feature request?

**Comment by adelsz** [comment]
Hmm, pgTyped doesn't wrap spreads with braces. See line 361 here (annotated SQL files test):
https://github.com/adelsz/pgtyped/blob/c51982b1ebfabeb09b43ea8511646170f9295aaf/packages/query/src/preprocessor-sql.test.ts#L344-L364
See line 311 here (TS file test)
https://github.com/adelsz/pgtyped/blob/c51982b1ebfabeb09b43ea8511646170f9295aaf/packages/query/src/preprocessor-ts.test.ts#L297-L319

**Comment by golergka** [comment]
Then it must be an issue with documentation, because [here](https://pgtyped.now.sh/docs/ts-file#array-spread-and-pick) you can clearly see as this exact example is supposed to be:

```sql
INSERT INTO users (name, age) VALUES (($1, $2), ($3, $4)) RETURNING id;
```

**Comment by golergka** [comment]
Fixed by https://github.com/adelsz/pgtyped/pull/152

**Comment by technic** [comment]
So does `UPDATE ... FROM (VALUES ...)` work without type cast in the end? It doesn't work for me for query in *sql file.
