### ISSUE TITLE
Possible improvement to README

### ISSUE THREAD

**Issue by gonzus** [adelsz/pgtyped#154]
From the example, I understood this is an error because `bookId` must be a number:

```ts
  const books = await findBookById.run(
    {
      bookId: 'carl-sagan-76',
    },
    client,
  );
```

If this is the case, maybe the `README` could clearly state that this will be caught as an error.

**Comment by adelsz** [comment]
Thanks for spotting it @gonzus 
Updated the README to have number for `bookId`.

**Comment by gonzus** [comment]
Glad to help. I am pretty sure I saw the same problem in the docs at https://pgtyped.now.sh/docs/sql-file-intro (and maybe other places?), so you may want to fix those as well.
