### ISSUE TITLE
Types not inferred for `= ANY()` construct

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#156]
When I used the following query:

```Typescript
const example = sql`SELECT column_name FROM table_name WHERE id = ANY($$IDs)`
```

I got the following type signature:

```Typescript
export interface IExampleParams {
  IDs: Array<never | null | void>;
}
```

(Notice the `never` type).

However, when I changed it to `IN()`:

```Typescript
const example = sql`SELECT column_name FROM table_name WHERE id IN($$IDs)`
```

I got the following type signature:

```Typescript
export interface IExampleParams {
  IDs: Array<number | null | void>;
}
```

And `never` is changed to `number` now.

(Table and column names changed in the example code, obviously).

**Comment by uhoh-itsmaciek** [comment]
I'm just playing with pgtyped to evaluate it, and also was interested in array handling and ran across your issue. It looks like you should be able to use regular params here, instead of parameter expansion, no? That is, if I write

```
/*
 @name Test
*/
SELECT name FROM books WHERE rank = ANY (:ranks);
```

I get

```
/** 'Test' parameters type */
export interface ITestParams {
  ranks: numberArray | null | void;
}
```

which seems right.

**Comment by adelsz** [comment]
Closing as stale, please reopen if @uhoh-itsmaciek solution doesn't work.
