### ISSUE TITLE
How to make dynamic query?

### ISSUE THREAD

**Issue by redinggg** [adelsz/pgtyped#157]
There is some kind of sql query
```sql
SELECT * FROM games WHERE status = :status AND rounds > :rounds AND ... ORDER BY id DESC LIMIT 10
```
I want to do something like:
```javascript
const games = getGames.run({
  where_column: 'status = true AND rounds > 10 AND ...', // optional
  order_column: 'id desc', // optional
  limit: '10' // optional
}, client)
```
```sql
SELECT * FROM games WHERE :where_column ORDER BY :order_column LIMIT :limit
```

I apologize if I explained crookedly

**Comment by adelsz** [comment]
Unfortunately, queries can't be composed in pgTyped, they need to be made dynamic at the SQL level.
See these two issues for how to achieve that for sorting and filtering: https://github.com/adelsz/pgtyped/issues/123 https://github.com/adelsz/pgtyped/issues/111.

**Comment by wongjiahau** [comment]
@adelsz I think this idiom should be included in the main documentation
