### ISSUE TITLE
Very long generated names for SQL-in-TS

### ISSUE THREAD

**Issue by chmln** [adelsz/pgtyped#160]
Example:
```ts
sql`
insert into users(email, stripe_id, password)
values($email, $stripe_id, $password)
returning *
`
```

Generated:
```ts
export interface ISqlSignupQueryInsertIntoUsersEmailStripeIdPasswordValuesEmailStripeIdPasswordReturningQuery {
  params: ISqlSignupQueryInsertIntoUsersEmailStripeIdPasswordValuesEmailStripeIdPasswordReturningParams;
  result: ISqlSignupQueryInsertIntoUsersEmailStripeIdPasswordValuesEmailStripeIdPasswordReturningResult;
}
```

That's 92 characters. 

I tried including a comment with `@name` but it didn't have any effect. It would be great if it worked and allows users to give names to queries.

**Comment by adelsz** [comment]
Hi @chmln,
`@name` directives only work in SQL files.
In TS files, queries are names after their TS variable names.
Example:
```ts
const myOwnCustomQuery = sql`
insert into users(email, stripe_id, password)
values($email, $stripe_id, $password)
returning *`;
```
Should generate:
```
export interface IMyOwnCustomQuery {
 ....
}
```
Can you post a code sample of how you define your TS query?

**Comment by chmln** [comment]
Hey @adelsz thanks for getting back so quickly, and you work on `pgTyped`.

That makes sense now as I'm using my own wrapper for `sql`.

Here's what I got:

```ts
export const sql = <T extends ITypePair>(query: TemplateStringsArray) => (
    params: T["params"]
) => pg_sql<T>(query).run(params, DB_POOL);
```

Is there a way to use custom query names in this case?

**Comment by adelsz** [comment]
Ok, so it looks like you are trying to build something like a wrapper with a bound pool instance.
Will something like this work for you:
```ts
export const sqlx = <T extends TTypePair>(query: TaggedQuery<T>, params: T["params"]) => (
  query.run(params, DB_POOL)
);

// Usage:
const myOwnCustomQuery = sql`
insert into users(email, stripe_id, password)
values($email, $stripe_id, $password)
returning *`;

const result = await sqlx<IMyOwnCustomQuery>({ email: ..., stripe_id: ... });
```

Note that pgTyped scans your files for an `sql` templated literal. For this to function properly it is best avoid using an `sql` name for your own functions or literals.

**Comment by chmln** [comment]
@adelsz thanks for the workaround! I played around with possible solutions a bit.

It looks like there is a hard requirement in the parser to have something of the form of 
```ts
const query = sql`...`
```

Which means I can't do 
```ts
const insertUser = await sqlx(
    sql`
    insert into users(email, stripe_id, password)
    values($email, $stripe_id, $password)
    returning *
`,
    {
        email,
        password,
        stripe_id,
    }
);

```

I think it would be a nice usability improvement to make concise statements like mine possible. Splitting up is totally okay but introduces some redundancy imo.

Would you be open to allowing something like `/* @name Signup */` in the `sql` template literals? I wouldn't mind helping out and submitting a PR.

**Comment by adelsz** [comment]
Sorry for the late reply @chmln. We can allow `@name` declarations in TS literals as a workaround for your specific usecase. Please feel free to open a PR.
