### ISSUE TITLE
Suggestion: command line option to generate type definitions only for a particular file

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#163]
I am porting a faily big project to use pgtyped, and I need to re-generate type definitions as I edit the SQL. However, although I'm interested in generating type definitions only for a particular file (and may be only for a particular query), editing config for it is very cumbersome each time, and the whole re-generation process for all the files is pretty long.

It would be a great workflow improvement if there would be a command line option that would override the config file in that regard.

I can implement it myself, if you'd aprove that feature.

**Comment by adelsz** [comment]
I think that would be useful, something like a single-file flag
