### ISSUE TITLE
Feature request: parameters on fields with NOT NULL constraint should not be nullable

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#179]
Right now, when I write a query to insert a row into a table with NOT NULL constraint still generates parameter types that contain `| null | void` at the end. It would be very helpful if pgquery would detect such constraints and make generated types non-nullable.

**Comment by adelsz** [comment]
This would be great to have.
Unfortunately postgres doesn't provide nullability data for param types so it doesn't seem possible at the moment.
We might add a heuristic that does that for very simple insert queries, but it won't be possible for anything more complicated.
Also see #118
