### ISSUE TITLE
returning values not being correctly converted to camel case

### ISSUE THREAD

**Issue by twk** [adelsz/pgtyped#181]
I've got this query:

```
/* @name createCustomer */
insert into customers (name) values (:name) returning customer_id, name;
```

Which generates the return value I expect, with camel casing turned on:
```
export interface ICreateCustomerResult {
  customerId: number;
  name: string;
}
```

But when I run this code:
```
    const res = await createCustomer.run(payload, this.globalPool);
    console.log(JSON.stringify(res))
```

I get back a row that has not been converted to camel case:
```
    [{"customer_id":1,"name":"cust_0a8d48a7afd83b63"}]
```

Am I doing something wrong here, or is this a bug?

**Comment by darky** [comment]
I implement this feature only on compile-time level. For runtime you should write own converter

**Comment by adelsz** [comment]
@twk Camel-case conversion is an experimental feature and is compile-time only.
Runtime conversion is not supported out of the box yet, but third-party modules like [this one](https://www.npmjs.com/package/pg-camelcase) might be helpful in the meantime
