### ISSUE TITLE
support json_build_object

### ISSUE THREAD

**Issue by benawad** [adelsz/pgtyped#182]
I got the following error which I assume is from using `json_build_object`
![image](https://user-images.githubusercontent.com/7872329/92963230-c1cc6d00-f437-11ea-9db3-aca3e9cc900d.png)

my query looks something like this

```sql
select array(select json_build_object('text', text) from posts)
from users;
```

**Comment by adelsz** [comment]
It looks like the result of this query is an array of jsons.
Adding PG array support to pgTyped is a work in progress: #144 

I think converting the whole result (including the array) to JSON should work though:
```sql
select json_agg(posts) from posts;
```
http://sqlfiddle.com/#!17/83505f/16

**Comment by benawad** [comment]
Thanks, `json_agg` is slick!

Now the type is `Json`, is there any way to get a better type than that (didn't see anything on it in the docs)?

btw on dynamic conditions, 
```sql
select * from posts
where (ms.name = :name or :name is NULL);
```
works, but 
```sql
select * from posts
where (:name is NULL or ms.name = :name);
```
gives 
![image](https://user-images.githubusercontent.com/7872329/92979756-4e3b5780-f459-11ea-9ff5-a88953e18fa3.png)

**Comment by adelsz** [comment]
>  on dynamic conditions

Unfortunately that is a quirk of the postgres type inference, not much we can do about it.

> is there any way to get a better type than that

In Postgres JSON is untyped by design. What you might want is PG [composite types](https://www.postgresql.org/docs/9.1/rowtypes.html), but those are still unsupported and rarely used.
