### ISSUE TITLE
Source path formatted differently in watch vs synchronous mode

### ISSUE THREAD

**Issue by danielbrauer** [adelsz/pgtyped#185]
Executing pgtyped in watch mode results in the following comment:

```/** Types generated for queries found in "src/queries/comments.sql" */```

Whereas without `-w`, the output is this:

```/** Types generated for queries found in "./src/queries/comments.sql" */```

I use both depending on my workflow, and generally speaking it would obviously be better if they matched.

My config file looks like this:

```
{
    "transforms": [
      {
        "mode": "sql",
        "include": "**/*.sql",
        "emitTemplate": "{{dir}}/{{name}}.gen.ts"
      }
    ],
    "srcDir": "./src/",
    "failOnError": false,
    "camelCaseColumnNames": true,
    "db": {
      "host": "localhost",
      "user": "",
      "dbName": "instead",
      "password": ""
    }
  }
```

**Comment by golergka** [comment]
Oh, I've seen these exact change happening sometimes, but blamed it on using a different OS than my colleagues! Thanks for figuring it out.
