### ISSUE TITLE
Count aggregate function is `number | null`, should be just `number`

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#191]
So, I have this straightforward query:

```Typescript
const someCountQuery = sql<ISomeCountQuery>`
	SELECT COUNT(*)::int AS count
	FROM someTable
	WHERE someCondition = TRUE
```

However, it's result type is:

```Typescript
export interface ISomeCountQuery {
	count: number | null
}
```

Shouldn't it just be number? Even if there are 0 rows satisfying the condition, the `COUNT(*)` aggregate function should be returning 0, not null.

**Comment by adelsz** [comment]
We rely on the Postgres type inference engine, and it￼ ￼looks like it returns a nullable integer type in this case. You can verify this by running a describe in the psql cli.
Going forward, I will be collecting a list of all such inconsistencies to see if someone on the Postgres team will be interested in fixing them at some point.
