### ISSUE TITLE
`coalesce` with a literal, non-null value is generating a `| null` type

### ISSUE THREAD

**Issue by mako-taco** [adelsz/pgtyped#197]
Some aggregate functions can return null if there are no rows returned, so it makes sense that the following would generate a `| null` type for `total_score`:

```
select sum(score) as total_score from users
```

However, it is impossible for this to return a null value for `total_score`:

```
select coalesce(sum(score), 0) as total_score from users
```

However, the generated type is still `number | null`.

Perhaps this could be solved with a new annotation, if it's not easy to determine if the function can return null or not.

**Comment by darky** [comment]
@mako-taco you can transform pgtyped types to something another with tools like https://github.com/millsp/ts-toolbelt

**Comment by adelsz** [comment]
Thanks for reporting this behavior. Closing it for now, since we can't do much about it at this stage.
It will still be tracked in this meta issue: https://github.com/adelsz/pgtyped/issues/375
