### ISSUE TITLE
Suggestion: use type-fest's CamelCase to convert database types in snake case to typescript types in camel case

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#199]
It's customary to use snake case in SQL and camel case in Typescript. Now, when we use pgtyped it means that we either have snake case identifiers leaking to Typescript, or have to define each SQL column, for example, called "some_column" with "AS someColumn" in the query.

It looks as if [type-fest's camel case](https://github.com/sindresorhus/type-fest#template-literal-types) could be used to convert the properties between camel and snake case automatically.

**Comment by adelsz** [comment]
Thanks for the suggestion @golergka
This is a good idea, we will have to keep it under a CLI feature flag to make sure it doesn't break on older TS versions.
