### ISSUE TITLE
sort enum types alphabetically so that type files are generated deterministically

### ISSUE THREAD

**Issue by carlpeaslee** [adelsz/pgtyped#204]
Our team uses pgtyped and we are getting lots of churn on pull requests and in git because the ordering of enums isn't deterministic. 

Would love to make a PR to sort the enums type values alphabetically.

**Comment by adelsz** [comment]
Thanks @carlpeaslee, that would be great, let me know if you will need any help with that

**Comment by carlpeaslee** [comment]
Cool lemme know if I got the PR right!

**Comment by adelsz** [comment]
Thanks @carlpeaslee, PR merged!
