### ISSUE TITLE
Use prettier to format generated output

### ISSUE THREAD

**Issue by travigd** [adelsz/pgtyped#211]
If installed, pgtyped should automatically run its output through prettier.

**Comment by RXminuS** [comment]
Voting against this. You can always run whatever linter you want on a glob pattern that matches the generated output. We're using ESLint for instance. Don't feel it's core to this project. But just my 2ct

**Comment by liujimj** [comment]
If you're running pg-typed, you've already decided to run a command every time your schema changes. Running a script that also runs Prettier seems like the right approach.

**Comment by smallnamespace** [comment]
If you're running pgtyped, you've already committed to running a command every time your schema changes. Running a script instead (to run pgtyped, then prettier) seems like the simplest approach.

**Comment by adelsz** [comment]
Agree with @RXminuS. Linting/prettifying is opinionated and is best done outside pgtyped.
