### ISSUE TITLE
Feature proposal: sort enum values and do one line per value

### ISSUE THREAD

**Issue by golergka** [adelsz/pgtyped#212]
Sometimes, when I run pgtyped, I get a lot of diffs that look like this:

```
-export type status = 'CREATED' | 'FINISHED' | 'LIVE'
+export type status = 'CREATED' | 'LIVE' | 'FINISHED'
```

May be it's related to the fact that we re-dump and apply schema production to development database from time to time, but since those two are functionally equivalent, it would be nice to sort enum values so that this diff wouldn't happen.

In fact, this would be much better to make diffs even more readable:

```Typescript
export type status =
    | 'CREATED'
    | 'FINISHED'
    | 'LIVE'
```

**Comment by adelsz** [comment]
Fixed in v0.10.1!
