### ISSUE TITLE
Enum arrays are unsupported

### ISSUE THREAD

**Issue by johannesfritsch** [adelsz/pgtyped#218]
I saw you added array support in #172. Yet we are still missing enum arrays. Are these a planned feature? It is quite common to have enum arrays for things like "allowedAuthMethods" (with values such as [NONE, JWT, SOMEOTHER]). Would love to hear some feedback.

We are not familiar with the codebase, but if it helps I can spend an hour or two trying to figure this out.

**Comment by adelsz** [comment]
Enum arrays would be great to have. They can probably be added as part of the existing type mapping framework here: https://github.com/adelsz/pgtyped/blob/0b90a730754d9caac31b401b68c3ed16e8ff0f1e/packages/query/src/actions.ts#L252

**Comment by benlongo** [comment]
Can this be closed?
