### ISSUE TITLE
Replacing Json with better interfaces

### ISSUE THREAD

**Issue by mattkrick** [adelsz/pgtyped#219]
Love the project! I see that PG uses unstructured Json by design (https://github.com/adelsz/pgtyped/issues/182#issuecomment-694469675). I was thinking about submitting a PR to fix this & wanted to get your blessing before starting.

In PG, it's possible to validate Json using a PG extension that takes a JSON schema v4. For example:
- https://github.com/furstenheim/is_jsonb_valid 
- https://github.com/gavinwahl/postgres-json-schema.

I can get that JSON schema by querying the constraint def via  `pg_get_constraintdef`

I can turn that JSON schema into typescript using https://github.com/bcherny/json-schema-to-typescript

Does this sound like something you'd accept? Any guidance on getting started?

**Comment by adelsz** [comment]
The benefit/complexity ratio for adding this is probably too low. I will be happy to reconsider if PG will  support typed JSON natively at some point.
