### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by wimpheling** [adelsz/pgtyped#224]
That looks bad !
https://pgtyped.now.sh/
![PgTyped-Typesafe-SQL-in-Typescript-PgTyped](https://user-images.githubusercontent.com/471188/109110450-7680ef00-7737-11eb-9569-19aa2b10c053.png)

**Comment by adelsz** [comment]
Thanks @wimpheling, I wasn't aware of that, looks like there was a bug in Docusaurus. Fixed by upgrading.
