### ISSUE TITLE
pgtyped hangs after initial DB connection 

### ISSUE THREAD

**Issue by eh-dub** [adelsz/pgtyped#225]
pgtyped will run for about 60 seconds in watch mode. 59 of those seconds are apparently doing nothing after these logs print:
<img width="644" alt="Screen Shot 2021-02-27 at 4 26 12 PM" src="https://user-images.githubusercontent.com/846035/109400772-9b808800-7918-11eb-93b9-1c8b6ce64b93.png">
Here is my config file:
```
{
  "transforms": [
    {
      "mode": "sql",
      "include": "**/*.sql",
      "emitTemplate": "{{dir}}/{{name}}.queries.ts"
    }
  ],
  "srcDir": "./sql",
  "failOnError": true,
  "camelCaseColumnNames": false,
  "dbUrl": "my-db-url",
  "db": {
    "ssl": false
  }
}
```
I censored my actual DB URL for this post.

I'm using a Heroku Postgres database.

**Comment by eh-dub** [comment]
I set up a local postgresql and had no problems. Am still curious to know what the difference is but it's not urgent.

**Comment by mako-taco** [comment]
A colleague of mine is seeing this as well, without watch mode. Identical config file.

They have been able to do everything else in our repo which requires connections to the same database.

**Comment by kklas** [comment]
FWIW had the exact same issue and it was related to scram-sha-256 not being supported #235. Once I switched to md5 it worked.

I would assume Heroku also uses scram so that's why it didn't work on Heroku for OP.
