### ISSUE TITLE
dbUrl does not work

### ISSUE THREAD

**Issue by ludusrusso** [adelsz/pgtyped#227]
Hi, 
I'm trying to connect to ad DB using the dbUrl field in configuration file but it does not work

```json
{
  "transforms": [
    {
      "mode": "sql",
      "include": "**/*.sql",
      "emitTemplate": "{{dir}}/{{name}}.queries.ts"
    }
  ],
  "srcDir": "./src/",
  "failOnError": false,
  "camelCaseColumnNames": false,
  "dbUrl": "postgres://postgres:postgres@localhost:5432/postgres"
}
```

I got this errors: 

```
Error in query. Details: {
  errorCode: 'parserOpenTable',
  hint: undefined,
  message: 'relation "engines" does not exist',
  position: '54'
}
```

But it works perfectly if I use the db object instead!

**Comment by adelsz** [comment]
Can you please share the db object config version as well?

**Comment by ludusrusso** [comment]
```
module.exports = {
  transforms: [
    {
      mode: 'sql',
      include: '**/*.sql',
      emitTemplate: '{{dir}}/{{name}}.queries.ts',
    },
  ],
  srcDir: './src/',
  failOnError: false,
  camelCaseColumnNames: false,
  db: {
    dbName: 'postgres',
    user: 'postgres',
    password: 'postgres',
    host: 'localhost',
    port: 5432,ì
    ssl: false,
  },
};
```

Tested both in js and json

**Comment by ludusrusso** [comment]
I think that it is not reading the dbUrl field and connecting to a default database.

**Comment by ludusrusso** [comment]
I changed the dbName, that is not `postgres` but a different name.

**Comment by ludusrusso** [comment]
@adelsz I've tested with source code and it works well. Is it possible that #205 has not been released? I'm using `@pgtyped/cli@0.10.1` that is the latest version available on npm!

**Comment by adelsz** [comment]
You are right, seems like v0.10.1 was built from an older commit. Pushed a new version (v0.10.2) which fixes that.
Let me know if the issue persists.

**Comment by ludusrusso** [comment]
Great! It works :D
