### ISSUE TITLE
Inconsistent directory seperator in .types.ts files

### ISSUE THREAD

**Issue by AlexHorstkoetter** [adelsz/pgtyped#230]
The directory seperators in the header of the types files are inconsistent between windows and linux:

Windows: `/** Types generated for queries found in "src\repositories\some-repository.ts" */`
Linux: `/** Types generated for queries found in "src/repositories/some-repository.ts" */`

This is somewhat annoying for version control

**Comment by adelsz** [comment]
Fixed in v0.10.3. I wasn't able to fully test as I dont have a Windows machine available. Let me know if the issue persists.
