### ISSUE TITLE
[Question] Generate types from schema without target a running database

### ISSUE THREAD

**Issue by ludusrusso** [adelsz/pgtyped#231]
like [sqlc](https://github.com/kyleconroy/sqlc) does, it would be possible to target a schema.sql file instead a read database? It would be helpful in CI/CD jobs

**Comment by adelsz** [comment]
Looks like sqlc uses a custom built parser for SQL.
We might be adding a custom parser for simple queries in the future, but for now we rely on PostgreSQLs type inference.

As a temporary workaround I would suggest spinning up a lightweight PG container to provide the types in a CI/CD setting.

**Comment by ludusrusso** [comment]
Yea! Spinning a light docker based Postgres is what I'm doing now. Thanks :)
