### ISSUE TITLE
SQL string template expansion support

### ISSUE THREAD

**Issue by jadbox** [adelsz/pgtyped#237]
The NPM library `postgres` has a really nice feature to do string template expansions, can read about it here:
https://github.com/porsager/postgres

For example:
```
const users = await sql`
  select 
    * 
  from users
  where age in (${ [68, 75, 23] })
`
```

In theory, pgtyped, should be able to do something just like this too, and it would help with general ease of development.

**Comment by adelsz** [comment]
Unfortunately, this would make PG type inference impossible. Related https://github.com/adelsz/pgtyped/issues/233
