### ISSUE TITLE
Example's schema.sql execution?

### ISSUE THREAD

**Issue by delaneyj** [adelsz/pgtyped#271]
The docs say...

> The dockerized setup isn't required and is included for convenience.
> ***It creates a PostgreSQL DB, loading it with the schema and seed records defined in sql/schema.sql.***
> After that it starts PgTyped in a separate container, connecting it to the DB.

But search through the setup I'm not seeing where `schema.sql` get initialized anywhere.

**Comment by adelsz** [comment]
The `sql` folder is mounted at the docker postgres init directory here:
https://github.com/adelsz/pgtyped/blob/c89ed1e887b911f1cfebaa3b06b03bcd7137d598/packages/example/docker-compose.yml#L14
