### ISSUE TITLE
exclude option?

### ISSUE THREAD

**Issue by delaneyj** [adelsz/pgtyped#272]
I have a situation where I want to enable watching on entire `src` dir except one folder (migrations).  Would it be possible to add an `exclude: string[]` option to the config files?

**Comment by adelsz** [comment]
Can excluding the directory using the `transform.include` glob pattern solve this?

**Comment by delaneyj** [comment]
Maybe?  I saw `include` is a string string and not an array so didn't know the story with having multiple globs to check.  Like ignore `migrations` and `node_modules` for example.

**Comment by adelsz** [comment]
Include is a [glob](https://www.npmjs.com/package/glob) string that you can use to ignore some files or directories.
> !(migrations|node_modules) Matches anything that does not match any of the patterns provided.

Let me know if this doesn't cover your case.

**Comment by kenberkeley** [comment]
The current match pattern:

https://github.com/adelsz/pgtyped/blob/17401646398b2860174f716812e1a9712efe3749/packages/cli/src/index.ts#L133

... does not cover my case in a monorepo.

***

This is my monorepo's folder structure:

```
.
├── node_modules/
├── packages/ <-------------------- config.srcDir
|     ├── client/
|     |     ├── node_modules/
|     |     ├── src/
|     |     └── package.json
|     ├── server/
|     |     ├── node_modules/
|     |     ├── src/
|     |     └── package.json
|     └── shared/
|           ├── node_modules/
|           ├── src/
|           └── package.json
├── package.json
└── yarn.lock
```

My config:

* `config.srcDir` is the `packages` folder
* `transform.include` is `"src/**/*.ts"`

So the `pattern` is `<path_to>/packages/**/src/**/*.ts`

***

The use of `/**/` will include `node_modules` in each package.
