### ISSUE TITLE
Use with different postgres clients

### ISSUE THREAD

**Issue by maxpain** [adelsz/pgtyped#276]
I want to use pgtyped with [Postgres.js](https://www.npmjs.com/package/postgres), but seems it's impossible because of this:

https://github.com/adelsz/pgtyped/blob/c89ed1e887b911f1cfebaa3b06b03bcd7137d598/packages/query/src/tag.ts#L7-L9

**Comment by bradleyayers** [comment]
Have you looked at [`sql.unsafe`](https://github.com/porsager/postgres/blob/0eff017eaf73a6790c550e94250342f1b14bc450/types/index.d.ts#L383). I haven't tried it, but it looks like you should be able to write something like this:

```ts
const sql = postgres(/* … */);
const databaseConnection: IDatabaseConnection = {
  query: async (query, bindings) => {
    return { rows: await sql.unsafe(query, bindings) };
  }
};
```

**Comment by aN00B1s** [comment]
If anyone has run into this issue, you can find the npm package here: 
[postgres-bridge](https://github.com/gajus/postgres-bridge)
