### ISSUE TITLE
failOnError doesn't fail?

### ISSUE THREAD

**Issue by jgonera** [adelsz/pgtyped#286]
Using version 0.11.0 I set `failOnError: true` in my config and tried writing a `select` query that fetches a column that doesn't exist. `npx pgtyped` showed an error but still generated a corresponding `.ts` file and exited with status 0:

```
$ npx pgtyped --config pgtyped.config.js
Processing src/db/queries/test.sql
Error in query. Details: {
  errorCode: 'errorMissingColumn',
  hint: 'Perhaps you meant to reference the column "test.name" or the column "test.type".',
  message: 'column test.nope does not exist',
  position: '10'
}
Saved 1 query types to src/db/queries/test.ts
$ echo $?
0
```

Am I doing something wrong? How can I make pgtyped exit with a non-zero status when this happens and, preferably, not generate a `.ts` file with an invalid query?

Edit: After a closer look types are set to `never` for an invalid query, but I'd still prefer the CLI to exit with a non-zero status if there are errors.

**Comment by wongjiahau** [comment]
I'm also facing this issue, this is important for CI/CD pipeline

**Comment by adelsz** [comment]
Fixed in https://github.com/adelsz/pgtyped/commit/aada874f55f84f9caf290800b7d45de9e1c59ea4.
