### ISSUE TITLE
Normal comments don't work in .sql files

### ISSUE THREAD

**Issue by isaac-leonard-uni** [adelsz/pgtyped#300]
It seems as though the parser is trying to read annotations from normal comments even when the @ symbol isn't used so:
-- Copied from https://stackoverflow.com/a/7745635 
Gives this error
(2:21) Parse error: extraneous input '//' expecting ID
It looks like its reading the ":" as a prompt for a labeled input to a query.
The same happens with multiline comments

**Comment by isaac-leonard-uni** [comment]
I mainly wanted to add general comments to explain the code with no metadata tags

**Comment by blaenk** [comment]
I find myself wishing I had this a few times every so often. I try it, then things break and I remember I can't use regular comments.

The reason I'd like to use comments would be to explain complex and/or large queries, for example.

**Comment by AlexHorstkoetter** [comment]
as a workaround you can use SQL comments, e.g `-- some comment`

**Comment by blaenk** [comment]
Hmm, but that's the very kind of comment that I would try to use, which would fail. I'll have to try again.

**Comment by wongjiahau** [comment]
@blaenk I managed to get it working by putting the comments in between the SQL queries.

**Comment by bradleyayers** [comment]
Comments do work, unless they contain tokens that have special meaning by pgtyped (e.g. `:`, `'`).

**Comment by bradleyayers** [comment]
I've raised #408 to add support for line comments, I was running into this problem too.
