### ISSUE TITLE
Postgres type 'time' is not properly supported

### ISSUE THREAD

**Issue by joecarver** [adelsz/pgtyped#310]
Hello there, thank you for the fantastic library.

We have an issue with a column of type `time`. pgTyped converts this to the Typescript type `Date`, which is not compatible. Dates in JS must contain both date and time, and if you try and insert a `Date` object to a `time` column, the pg parser throws a `DateTimeParseError`, for example:

```
error: invalid input syntax for type time: "2021-01-01T09:00:00.000+00:00"
```

Postgres `time` values must take the format `HH:mm:ss` e.g. `09:00:00`. I believe there isn't a suitable default type in Typescript for this, except of course `string`, so I suppose my suggestion would be to use the `string` TS type instead of `Date`. 

Thank you!

**Comment by adelsz** [comment]
Type overrides have now been merged so a string override can be added.
