### ISSUE TITLE
Adding a query with a JsonArray type omits Json type from resulting Typescript file

### ISSUE THREAD

**Issue by bramkoot** [adelsz/pgtyped#323]
First of all, awesome work on getting this off the ground. This package delivers amazing value and seems to be quite stable overall. I used it with a lot of heavy and advanced queries that even used Postgres-extensions but everything worked out of the box so far.

I did find a very reproducible bug:

When you create a SQL query that fetches a Json field, pgtyped will add the (recursive) Json type to the Typescript file:

```
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
```

When you add a SQL query that fetches a JsonArray field, pgtyped will add the JsonArray type, which is recursive but depends on Json type. This type is not part of the file if you only select a JsonArray type:

```
export type JsonArray = (null | boolean | number | string | Json[] | { [key: string]: Json })[];
```

As a result the Typescript file will throw the `TS2304: Cannot find name 'Json'.` error. 

It would be great if this could be fixed. 

If anybody finds this issue and needs a hot fix right away; it's quite simple. To the existing SQL file add a query that fetches a Json field. You don't have to use the query (you can even name it 'donotusethisquery') but it will trigger the addition of the Json type to the Typescript file.

**Comment by AlexHorstkoetter** [comment]
Indeed it is

**Comment by adelsz** [comment]
Looks like a bug in the type processor. Thanks for reporting this @bramkoot.
