### ISSUE TITLE
cannot query JsonArray without querying Json

### ISSUE THREAD

**Issue by AlexHorstkoetter** [adelsz/pgtyped#326]
The generated code contains the type `JsonArray` if a query returns it.
It also contains the type `Json` if and only if a query returns it.
However, the type definition for `JsonArray` depends on `Json`: 
`export type JsonArray = (null | boolean | number | string | Json[] | { [key: string]: Json })[];`

So when I have a query that returns `JsonArray`  but no query that returns `Json`, I get a type error.

**Comment by bramkoot** [comment]
This is actually the same issue as #323
