### ISSUE TITLE
Coalesce type generated as nullable even if it's not

### ISSUE THREAD

**Issue by Sweater-Baron** [adelsz/pgtyped#327]
The type of a coalesce containing a constant is null. E.g. the type of coalesce(my_int_column, 123) is generated as "number | null" when it could just be number: The parser could look at this and see that 123 is a constant, so the coalesce will never be null.

A similar thing applies for a coalesce on a non-nullable column: coalesce(nullable_int_column, non_nullable_int_column) can be inferred as just a "number" type instead of "number | null".

**Comment by mako-taco** [comment]
see #197

**Comment by adelsz** [comment]
Thanks for reporting this behavior. Closing it for now, since we can't do much about it at this stage.
It will still be tracked in this meta issue: https://github.com/adelsz/pgtyped/issues/375
