### ISSUE TITLE
Queries with no parameters can't be executed as .run requires a paramter argument of type void

### ISSUE THREAD

**Issue by bag-man** [adelsz/pgtyped#329]
If I want to have the query: 

```
/* @name listKinds */
SELECT * FROM kind;
```

You can't call it with run as run expects a parameter for the params argument. 

I did a work around like this: 

```
/* @name listKinds */
SELECT * FROM kind WHERE (:id::uuid IS NULL OR id = :id);

const kinds = await listKinds.run({ id: null }, db)
```

But it would be great to swap the order of the variables and make params optional.

**Comment by KenSuenobu** [comment]
The argument type should be "null" and not "void".

**Comment by KenSuenobu** [comment]
Change the type from `void` to `null`, and that should work.  I tested it here, and it works okay with the same type of SQL query.

**Comment by bag-man** [comment]
That's not the case unfortunately: 

```
app/book.ts:66:39 - error TS2345: Argument of type 'null' is not assignable to parameter of type 'void'.

66     const kinds = await listKinds.run(null, db)
                                         ~~~~

```

As pgtyped generates 

```
/** 'ListKinds' parameters type */
export type IListKindsParams = void;
```

**Comment by blaenk** [comment]
I've been able to do this by passing `undefined`, but maybe I'm misunderstanding this issue.

**Comment by bag-man** [comment]
@blaenk You appear to be correct! I definitely did try that before but perhaps was on an older version. 

Maybe this should be added to the docs @adelsz?

Thanks!
