### ISSUE TITLE
What's the best way to handle create or update? 

### ISSUE THREAD

**Issue by lauraeci** [adelsz/pgtyped#331]
Finding that I'm writing a lot of logic around updating records based on the existence that might be considered a first or create or upsert. Update the first record but if that record doesn't exist I want to create it and wondering how others are handling this. Something like a PostgreSQL upsert? https://www.postgresqltutorial.com/postgresql-upsert/
Seems like there's nothing preventing me from using upsert with pgtyped but is it a pattern that should be propagated everywhere? Thank you.

Example:

 I want to update a user, I try to naively do an update first.
`await updateUser(userAttributes)`
if the gid on userAttributes doesn't exist, then it fails and I need to do 
`await insertUser(userAttributes)`

I could try to pull the record user and if it doesn't exist create it. Most of the time when I want to update the user record, the record should be there.

Thank you. 

Example queries: 

```
/*
  @name updateUser
*/
UPDATE users
SET
    "lastName" = :lastName,
WHERE "gid" = :gid
RETURNING "gid";
```

```
/*
  @name insertUser
*/
INSERT INTO users( "lastName")
VALUES ( :name)
RETURNING *;
```

**Comment by adelsz** [comment]
> Seems like there's nothing preventing me from using upsert with pgtyped but is it a pattern that should be propagated everywhere?

Not sure if I understand the question. pgTyped does support upserts.

**Comment by lauraeci** [comment]
@adelsz nice! Thanks! Is it recommended or pgTyped isn't opinionated?

**Comment by adelsz** [comment]
pgTyped isn't opinionated on this. We try to support all valid SQL.
