### ISSUE TITLE
feat: allow operation name to be logged/tracked

### ISSUE THREAD

**Issue by wongjiahau** [adelsz/pgtyped#346]
## Problem
Currently, it is not easy to locate which file is responsible for which query during runtime (especially development), because only `query` and `bindings` are exposed to clients:
```ts
  export interface IDatabaseConnection {                                                                        
      query: (query: string, bindings: any[]) => Promise<{
          rows: any[];
      }>;
  }  
```

## Suggestion
Add an optional third parameter to `query`, named `meta`, which can include information such as the query name etc.

**Comment by adelsz** [comment]
Exposing operation name isn't compatible with the way queries invoke `pg` at the moment and refactoring the query interfaces would be a breaking change. Need to gather more demand for this request before implementing such major changes.
