### ISSUE TITLE
Error ECONNRESET

### ISSUE THREAD

**Issue by panwauu** [adelsz/pgtyped#358]
Hi,
I wanted to try pg_typed but I cannot execute it.
I tried:
- Using the example project with the database in docker
- Using my local environment
- Setting the encryption to "md5"

If i execute "npx pgtyped -c onfig.json" it takes abount one minute and then displays the following error:
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

My local config.json is:
```
{
  "transforms": [],
  "srcDir": ".",
  "failOnError": false,
  "camelCaseColumnNames": false,
  "db": {
    "database": "tac",
    "dbName": "tac",
    "user": "postgres",
    "host": "localhost",
    "port": 5432,
    "password": "password",
    "ssl": false
  }
}
```

**Comment by adelsz** [comment]
I will need to learn more about your environment (OS, Node version, pgTyped version), especially when you try to run it against the docker container. pgTyped runs against the same container as part of the CI process.

**Comment by adelsz** [comment]
Closing as stale.
