### ISSUE TITLE
Coerce null to undefined in query results

### ISSUE THREAD

**Issue by chrisdavies** [adelsz/pgtyped#371]
In TypeScript / JavaScript, I find it much more natural to deal with undefined and to avoid null altogether, however this library (which is excellent, thank you, by the way!) returns null, rather than undefined. It would be nice to have a config value `"coerceNullToUndefined": true` or something.

As is, I'm simply going to wrap the generated TypeScript in a helper that will iterate over the results and do the coersion for me. If you're interested in this feature, I can put a PR together.

Thanks!

**Comment by adelsz** [comment]
Thanks for flagging this @chrisdavies. In my opinion `null` is a better fit for pgTyped since it explicitly signifies the absence of a value and is produced in Postgres and the driver by default. A wrapper is generally the correct solution for such type conversions.

**Comment by maxpain** [comment]
@adelsz I also need this option.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5875582/153722027-af107cb4-de02-42f0-86a2-fe1105c36fa2.png">

https://github.com/sindresorhus/meta/discussions/7
