### ISSUE TITLE
Support for DATABASE_URL?

### ISSUE THREAD

**Issue by msakrejda** [adelsz/pgtyped#381]
Hi,

Just started with pgtyped and really enjoying it so far. Would you consider a PR to add DATABASE_URL support as an alias for PGURI? Many tools already support this.

Thanks,
Maciek

**Comment by uhoh-itsmaciek** [comment]
Also, any chance pgtyped could support .env files? Right now it's hard to use `dotenv` for this with pgtyped, since pgtyped is its own CLI. Loading a .env file with a --envfile flag to specify a different one could be really useful.

**Comment by tbo** [comment]
@uhoh-itsmaciek You can handle the `.env` use case with a script entry inside your package.json:
```json
    "pgtyped": "node -r dotenv/config ./node_modules/.bin/pgtyped -wc config.json",
```

**Comment by uhoh-itsmaciek** [comment]
@tbo oh that's great, thanks! I looked at using `dotenv`, but I missed you can use it like a wrapper like `env`.

I'd still love to have pgtyped fall back to DATABASE_URL if PGURI is not set. Happy to contribute a patch.

**Comment by adelsz** [comment]
@uhoh-itsmaciek A PR to use `DATABASE_URL` as an alias for `PGURI` would be welcome.
