### ISSUE TITLE
pgtyped doesn't see sql function call in SQL-in-TS mode

### ISSUE THREAD

**Issue by maxpain** [adelsz/pgtyped#388]
Hello.

If I export `sql` function using naming export everything works fine:
```typescript
import { sql } from '@pgtyped/query'

const getSomething = sql`SELECT * FROM users`
```

But I can't use naming exports in pgtyped packages [due to this problem](https://github.com/adelsz/pgtyped/issues/382),
so I have to use this approach:

```typescript
import pgtyped from '@pgtyped/query'

const getSomething = pgtyped.sql`SELECT * FROM users`
```
But in this case pgtyped doesn't generate typings.

**Comment by maxpain** [comment]
@adelsz could you please fix it?

**Comment by adelsz** [comment]
pgTyped now supports ESM.
