### ISSUE TITLE
Parsing bug: spaces required around =

### ISSUE THREAD

**Issue by danvk** [adelsz/pgtyped#430]
When I write this query:

```ts
const q = sql`SELECT * FROM comment WHERE id=$id`;
```

I get the following error from PgTyped:

```
Processing server/db/comments.ts
Error in query. Details: {
  errorCode: 'scanner_yyerror',
  hint: undefined,
  message: 'syntax error at or near "$"',
  position: '32'
}
```

If I put spaces around the `=` signs, the error goes away:

```ts
const q = sql`SELECT * FROM comment WHERE id = $id`;
```

Both forms should work -- I don't see why the spaces should be required.

**Comment by adelsz** [comment]
Looks like a lexing bug, will look into it.
