### ISSUE TITLE
UNION operator makes all fields on result type nullable

### ISSUE THREAD

**Issue by danvk** [adelsz/pgtyped#431]
The generated type for this query:

```ts
const q = sql`SELECT * FROM comment`;
```

has correct nullability information for all the fields on the table:

```ts
/** 'Q' return type */
export interface QResult {
  archived: boolean;
  author_id: string | null;
  content_md: string;
  created_at: string;
  id: string;
  // ...
}
```

When I add a `UNION` to the query, however:

```ts
const q = sql`SELECT * FROM comment UNION SELECT * FROM comment`;
```

then _all_ the fields in the return type become nullable:

```ts
/** 'Q' return type */
export interface QResult {
  archived: boolean | null;
  author_id: string | null;
  content_md: string | null;
  created_at: string | null;
  id: string | null;
  // ...
}
```

Looking at the [docs](https://www.postgresql.org/docs/current/queries-union.html) on `UNION`, I don't see why it would affect the nullability of any of these columns. The `QResult` interface should be the same for both queries.

This might be another one for #375

**Comment by adelsz** [comment]
Thanks for reporting. Added a reference to this bug to the meta issue. Closing for now since we can't really do anything about it yet. Make sure to follow https://github.com/adelsz/pgtyped/pull/377 as it will provide a workaround.
