### ISSUE TITLE
cli does not properly shut down or reuse worker processes

### ISSUE THREAD

**Issue by mauricedoepke** [adelsz/pgtyped#458]
At least on M1 macs thats the case with pgtyped version 1.0.0 and 1.0.1

They just become more and more and stay connected to the database till the database reaches its connection limit.
Then I have manually kill them.

https://user-images.githubusercontent.com/16628813/180087204-3c475aad-b04a-4a35-94d3-ae0fb70f9862.mov

**Comment by adelsz** [comment]
Thanks for reporting this @mauricedoepke. Fixed in v1.0.2.

**Comment by mauricedoepke** [comment]
@adelsz thanks for the fast fix
