### ISSUE TITLE
Usage with postgresql-client

### ISSUE THREAD

**Issue by filipecatraia** [adelsz/pgtyped#469]
Hey @adelsz,

I'm moving away from 'pg' for a while until they add ESM support. `postgresql-client` could be a drop-in replacement, but it doesn't satisfy the `IDatabaseConnection` constraint. Do you have any tips on how to make it work?

Thanks a lot!

**Comment by adelsz** [comment]
You can create your own structure to satisfy `IDatabaseConnection`, something like this:
```ts
const databaseConnection: IDatabaseConnection = {
  query: async (query, bindings) => {
    let rows = /* run query using your library of choice */;
    return { rows };
  }
};
```
