### ISSUE TITLE
Type generation fails for some characters

### ISSUE THREAD

**Issue by gilgardosh** [adelsz/pgtyped#471]
Generating types for queries using some characters (like `Í` or `א`) fails, with the error:
```
Error in query. Details: {
  errorCode: 'pq_copymsgbytes',
  hint: undefined,
  message: 'insufficient data left in message',
  position: undefined
}
```

Steps to reproduce:
run pgtyped for this query: 
```
SELECT *
FROM bank_transactions
WHERE currency = 'שקל';
```
or even this:
`SELECT 'Í';`

**Comment by adelsz** [comment]
Thanks for reporting this. Fixed in https://github.com/adelsz/pgtyped/commit/81be76924116b75b674aa47b4da1a7e6eda511f7.
