### ISSUE TITLE
Does typesOverrides work?

### ISSUE THREAD

**Issue by danvk** [adelsz/pgtyped#477]
I was excited to see the new `typesOverrides` option in pgtyped@1.1.0. However, I'm not sure it works as advertised?

I added the following to my `pgtyped.config.json` based on the config in `CLI.md`:

```json
  "typesOverrides": {
    "date": "string"
  }
```

Then I removed the following from my post-processing script:

```
| perl -pe 's/: Date/: string/' \
```

Now when I run pgtyped, I see the following sorts of diffs for all my queries:

```
-  created_at: string | null;
+  created_at: Date | null;
-  expires_on: string | null;
+  expires_on: Date | null;
   id: string;
```

in other words, the type override isn't working. I don't see any tests in #476 so it's hard for me to tell what the expected behavior is.

I'm definitely on the right version because `"hungarianNotation": false` worked great.

Some guidance on what sorts of types you can override would be helpful, for example I'd like to change `Json` → `any` and `JsonArray` → `any[]`.

**Comment by adelsz** [comment]
Thanks for flagging this.
I am a bit busy testing a big structural rewrite https://github.com/adelsz/pgtyped/pull/478, which should land this week as v2.0.0.
Will get back to this issue right after that. Meanwhile maybe @nick-keller has some ideas on what is going on.

**Comment by petetnt** [comment]
I ran into the same issue, the `typesOverrides` seemingly does nothing, or I don't now how to use it properly.

**Comment by nick-keller** [comment]
Before @adelsz merged my changes I used this in my `package.json` and it worked.
```json
{
  "devDependencies": {
    "@pgtyped/cli": "https://github.com/nick-keller/pgtyped/raw/patched/packages/cli/pgtyped-cli-1.0.2.tgz",
    "@pgtyped/query": "^1.0.1",
    }
}
```

I am now using:
```json
{
  "devDependencies": {
    "@pgtyped/cli": "^1.1.0",
    "@pgtyped/query": "^1.1.0",
  }
}
```

And it still works. I run `pgtyped -w -c pgtyped.json` and my config file looks like this:
```json
{
  "transforms": [
    {
      "mode": "sql",
      "include": "**/*.sql",
      "emitTemplate": "{{dir}}/{{name}}.queries.ts"
    }
  ],
  "srcDir": "./src/",
  "failOnError": true,
  "db": {
      ...
  },
  "typesOverrides": {
    "date": "string"
  }
}
```

**Comment by adelsz** [comment]
I have added e2e tests for type override testing https://github.com/adelsz/pgtyped/pull/481/files.
They are passing on master, and should work on 1.1.0 too.

To have the correct types (ts `string` for pg `DATE`) at **runtime** you should setup `pg` correctly:
```ts
pg.types.setTypeParser(pg.types.builtins.DATE, function(val) {
    return val;
})
```

To have the correct types (ts `string` for pg `DATE`) at **compile-time** you should add the following to your config:
```ts
  "typesOverrides": {
    "date": "string"
  },
```

@danvk & @petetnt you can try `2.0.0-alpha.1` that has just been released, just make sure you follow the README as there were some package name changes in v2.

**Comment by petetnt** [comment]
Ah, I assumed that the `setTypeParser` calls would have been automatically called on the used client, but that makes way more sense. Thanks @adelsz!

**Comment by adelsz** [comment]
Great, it works as expected for you now?

> Ah, I assumed that the setTypeParser calls would have been automatically called on the used client, but that makes way more sense. Thanks @adelsz!

Got it, I guess we should highlight this in the docs.

**Comment by danvk** [comment]
I figured out what was going on — I was overriding `date` instead of `timestamptz`. I imagine the latter is vastly more common in real applications, so perhaps the docs could be updated to use it as an example?

```json
{
  "typesOverrides": {
    "date": "string",
    "timestamp": "string",
    "timestamptz": "string"
  }
}
```

I've also been having trouble using `typesOverrides` to override the `jsonb` type, but I can open a separate issue for that.
