### ISSUE TITLE
-w flag should watch for config changes

### ISSUE THREAD

**Issue by petetnt** [adelsz/pgtyped#479]
Hi, first of all thanks for the great library!

As I was trying to get the `typesOverrides` work (see #476) I noticed that it's actually quite hard to get `pgtyped` notice certain configuration changes.

It would be nice that `-w` watch would also watch changes in the config passed (eg. the value passed via `-c` flag) and:

- Warn the user about configuration changes requiring restart or automatically forcing a restart
- Marking all files as changed eg. by saving the configuration change timestamp somewhere (where?) and processing all the files again by passing some kind of `forceUpdate` flag to https://github.com/adelsz/pgtyped/blob/b925392d650fce83bcc459632dce89fdaeab4c1d/packages/cli/src/worker.ts#L53.

**Comment by adelsz** [comment]
Added warn and exit on config changes https://github.com/adelsz/pgtyped/commit/2515f15b009bb68482e22e1d751987d09633639e.
Cleanly implementing full restart on config changes is tricky given the amount of pending promises the CLI has while watching. Also, config file changes should be quite rare so https://github.com/adelsz/pgtyped/commit/2515f15b009bb68482e22e1d751987d09633639e should be good enough for now.

**Comment by petetnt** [comment]
Thank you!
