### ISSUE TITLE
Improve typing customization

### ISSUE THREAD

**Issue by nick-keller** [adelsz/pgtyped#480]
Once again, amazing work on your part @adelsz!

Here are a few ideas for improving typing with pgtyped. I'm ready to do it but I wanted to have everyone's aproval on the idea before going further.

# Complex mappers
Today it supports basic TS types:
```json
{
  "typesOverrides": {
    "date": "string",
    "json": "any"
  }
}
```

It would be nice to be able to specify imported types in the fashion of what [GraphQL codegen does](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-resolvers#use-your-model-types-mappers).

```json
{
  "typesOverrides": {
    "date": "dayjs#Dayjs"
    "myEnum": "./types/enums.ts#MyEnum"
  }
}
```

❓ What should be the root of the relative paths?
❓ What should be the specs of the format?

# Different mapping for parameters
It would be nice to type parameters and return values differently, even if they are of the same PG type.
For instance `Decimal` are returned as `string` by PG, so all select should be typed as such, but when inserting, updating, or using it in a where clause PG accept both a string or a number.

- The default typing should reflect that
- The config file should also allow to override those types as well

❓ What should the config file look like exactly?
❓ What is the behavior expected if you only override one of the two?

# Customize generated types
Today is generates `interface` and `enum`, it would be nice to choose between `type` `interface` and even `class` and between `enum` and string union.

 types as well

❓ What should the config file look like exactly?

**Comment by nick-keller** [comment]
To sum it up we could have:

# For imports
- types that start with `./` are imports
- types that contain a `#` are imports
- imports that start with `./` are relative path to the config file, others are absolute imports
- imports can have 0 or 1 `#`, otherwise it throws
- an import that does not contain a `#` imports `default`
- an import that ends with ` as .+` is aliases
- all imports of the same package are merged

# For return vs parameter
- if you specify a string, both `return` and `parameter` are set
- if you specify only one key, the other keeps its default built in value

**Comment by adelsz** [comment]
All looks good. Alias imports are a bit too much in my opinion, so I suggest to not add them.
On an implementation note, we might want to introduce local per-query type overrides in the future, so lets keep that in mind when designing the implementation for these global type overrides.

**Comment by nick-keller** [comment]
Actually alisases are very useful to solve naming conflict. From my experience with GraphQLCodegen (from which this spec is inspired) it was very handy to get out of tricky situations.
Plus the cost seams very low once imports are implemented anyway.
We can start without and see what we do from there ;)

**Comment by jakewhelan** [comment]
Would really love to use this feature, any idea when it might be published to `npm`?

**Comment by nick-keller** [comment]
The PR #494 was merged 2 days ago, it should be good
