### ISSUE TITLE
Include Typescript 5 as a peer dependency of @pgtyped/cli

### ISSUE THREAD

**Issue by nicokunz** [adelsz/pgtyped#518]
**Describe the bug**
Using @pgtyped/cli@2.1.0 in a repository using typscript 5 displays the following during yarn install:

`@pgtyped/cli@2.1.0" has incorrect peer dependency "typescript@3.1 - 4`

**Expected behavior**
Pgtyped uses Typescricpt 5.0.4 so the expected behaviour is that typescript 5 would be an acceptable peer dependency of this project

Thanks for a great library :)

**Comment by adelsz** [comment]
Fixed in v2.2.0
