### ISSUE TITLE
Get count without parameter

### ISSUE THREAD

**Issue by proyb6** [adelsz/pgtyped#525]
**Describe the bug**
Missing property from string

It returned `[object Object]` instead of string which I have to use `object1[0].count`, is there a way to return only string?

**Expected behavior**
Should work without any parameter. Look like a bug from generated code.

**Test case**
SELECT COUNT(*)::int FROM posts WHERE active > 0

**Comment by adelsz** [comment]
Rows are returned as objects, you can customize this behavior by building a custom query executor.
