### ISSUE TITLE
Failed to parse array value SQL with range array subscript

### ISSUE THREAD

**Issue by kwatanabe1050** [adelsz/pgtyped#527]
**Describe the bug**

I wanted to select(update) array value with range subscript to slice array.

```sql
select (ARRAY[1,2,3,4])[2:3] as arr;

-- Postgresql v9.2.22 can return below value on pgAdminIII
-- '{2,3}'
```

But now it does not work on pgTyped.

**Expected behavior**

Success to generate queries code and run on Node as per.

> We can also access arbitrary rectangular slices of an array, or subarrays. An array slice is denoted by writing lower-bound:upper-bound for one or more array dimensions. For example, this query retrieves the first item on Bill's schedule for the first two days of the week:

[Postgresql Offcial Doc: 8.15.3. Accessing Arrays](https://www.postgresql.org/docs/9.2/arrays.html)

Is there escape charactor for `:` or other array query?

**Test case**

1. Setup `"@pgtyped/runtime": "^2.1.0",` and `"@pgtyped/cli": "^2.2.1",` on TS v5, Node v18 project and windows 10.

2. Create below sql and try to generate query 

```sql
/* 
 @name sliceArray
 */
select (ARRAY[1,2,3,4])[2:3] as arr;
```

3. Log shows below error and failed to create queries file

```sh
Parsed file:
1 | /*
2 |  @name sliceArray
3 |  */
4 > select (ARRAY[1,2,3,4])[2:3] as arr;
5 |
Errors:
- (4:26) Parse error: missing ID at '3'
```

**Comment by kwatanabe1050** [comment]
`select (ARRAY[1,2,3,4]) as arr;` and `select (ARRAY[1,2,3,4])[2] as arr;` can output so I feel `:` has problem.

**Comment by adelsz** [comment]
Fixed in https://github.com/adelsz/pgtyped/commit/cdfadfba855df446bb2d35a2642e152454e1eb33
