### ISSUE TITLE
Invalid types generated for Explain queries

### ISSUE THREAD

**Issue by danielz-mnx** [adelsz/pgtyped#530]
**Describe the bug**
The return type generated for an explain query like:
```sql
/* @name Explain */
explain select 1
```
is as follows:
```ts
/** 'Explain' return type */
export interface IExplainResult {
  QUERY PLAN: string | null;
}
```
and obviously this isn't valid TS.

**Expected behavior**
The type only needs quotes:
```ts
/** 'Explain' return type */
export interface IExplainResult {
  "QUERY PLAN": string | null;
}
```

**Comment by adelsz** [comment]
Fixed in https://github.com/adelsz/pgtyped/commit/f9704e094e22202040c49194e3f9a839484bf7d3
