### ISSUE TITLE
Running pgtyped on a computer with lots of cores causes runaway memory consumption

### ISSUE THREAD

**Issue by bhalonen** [adelsz/pgtyped#536]
**Describe the bug**
If you run pg-typed code gen on a computer with lots of cores, it starts threads for every one of the cores and runs out of memory.

**Expected behavior**
A pgtyped_config.json flag to limit max number of threads Piscana starts.

**Test case**
Hard to do without hardware

**Comment by adelsz** [comment]
Fixed in https://github.com/adelsz/pgtyped/commit/241073841454bd82621473bba805defd2465f8f3
