### ISSUE TITLE
npx could not determine which executable to run

### ISSUE THREAD

**Issue by karagraysen** [adelsz/pgtyped#541]
**Describe the bug**
The README and docs suggest using `npx` to use `pgtyped` however when running any `npx pgtyped ...` command the terminal returns the error:

```
$ npx pgtyped
> npm ERR! could not determine executable to run
```

**Expected behavior**

`npx pgtyped` should know which executable to run.

**Test case**

N/A.

**Comment by adelsz** [comment]
You should install `pgtyped` as per the readme before you are able to run it with `npx`.

**Comment by karagraysen** [comment]
@adelsz This goes against the very idea of npx:

>NPX is a NPM package runner. It allows developers to execute any Javascript Package available on the NPM registry without even installing it.

A warning/call out of this should be added to the README.

**Comment by adelsz** [comment]
@karagraysen I understand that. We should probably replace `npx` with `npm run` to avoid confusion.
Running pgTyped without installing it doesn't make much sense, since the codebase queries require pgTyped to be installed anyways.
