### ISSUE TITLE
Infer field names for object pick

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#62]
When you have a long list of columns for example in an `INSERT INTO` query you end up having to write down the same long list twice. Once in the parameter pick expansion and once in the query. It would be nice to have a parameter expansion that expands both the values and the keys of an object. Something like:

```sql
/*
  @name insertUsers
  @param users -> ((name, age)...)
*/
INSERT INTO users ::users VALUES :users RETURNING id;
```

Possible syntax for the keys: `::users`, `:keyof:users`, `:users.keys`, `:users:keys`, would any of these be ambiguous?

**Comment by silasdavis** [comment]
Ah I just read:

> Expansion inference: allow required expansions to be inferred at compile time.

from the roadmap so clearly something like this or more powerful is on the cards. Would this still be a good first step? We could layer the inference steps so that this becomes and intermediate expression with the option of omitting parameters altogether as in:

```sql
/*
  @name insertUsers
  @param users -> (()...)
*/
INSERT INTO users VALUES :users RETURNING id;`;
```

If PgTyped was giving type safety of parameter names/types then the no-column variant would be fine (i.e. safe) in postgres, but that only works if you want to insert complete rows.

**Comment by adelsz** [comment]
Copying very long param lists can indeed be a bit ugly, but it is probably an OK compromise at the moment.

The main issues I see with adding this are:
1. Passed object keys may or may not be equal to inserted column names.
2. Potential issues/ambiguities that can arise from overloading query param syntax.
