### ISSUE TITLE
Union types for enums

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#65]
Slight buyers remorse from me (shame I didn't think of this a bit earlier!): an issue with using Typescript enums for database enums is that the types we generate in different files are incompatible. That is, Typescript considers them to be different types when in fact they represent the same underlying type.

This ends up feeling quite clumsy if you are passing otherwise compatible objects around because you end up having to convert enum types; `payloadType as string as PayloadTypeFromQuery2`.

We could instead use unions, so:

```typescript
export const enum PayloadType {
  Message = 'Message',
  Dynamite = 'Dynamite',
}
```

becomes:

```typescript
export type PayloadType = 'Message' | 'Dynamite';
```

This means that we would get type-safety on enums and type arguments referencing the same database enum would be compatible.

We would loose the runtime abilities of a enum doing this though. Some thoughts on options:

1. Switch entirely to unions
2. Generate string enums for each type but make the parameters/returns be of union type
3. Attempt to 'globalise' enums across generation of different files sharing a enum so that the enum definition is hoisted to some location where it can be imported by all queries that use that enum

I am leaning towards 1 being a better default. We can also give an option to generate enums (but maybe we should favour simplicity and drop support for now). It maintains generated file locality and mostly 'just works'. If someone needs a runtime enum or prefers the enum syntax (which does feel clearer and more conventional) they can always create one.

2 is an attempt at the best of both worlds, but it feels a bit weird generating enums that we don't actually use directly, it won't be obvious that you can use them, and you'll loose editor/IDE support.

3 might be cleanest for a codebase but feels like scope creep and without knowing/assuming a lot more about a project structure would be hard to do.

**Comment by silasdavis** [comment]
Hmm... option 4/improved option 2 (perhaps):

```typescript
export const enum PayloadTypes {
  Message = 'Message',
  Dynamite = 'Dynamite',
}

# We include the values of the enum in a union to allow type-compatibility between files that
# redeclare the same wrapper enum above, but provide the actual enum as a type hint and for use
# in code.
export type PayloadType = PayloadTypes | 'Message' | 'Dynamite';
```

This would give you autocompletion and IDE support as well as type compatibility. You can use the local enum or any of its values. Enums from other files would work as if they were compatible. It's a _slight_ hack, but this feels sort-of okay for generated code, what do you think?

**Comment by adelsz** [comment]
Right, I missed that too. I think the correct solution here is to switch entirely to literal string unions. This will also allow us to handle rare postgres enums that contain spaces or unicode.

**Comment by silasdavis** [comment]
@adelsz I think we need to revisit this, the ergonomics are still quite bad. You still have to case a string literal for this to work (which I assumed you would not - see https://stackoverflow.com/questions/37978528/typescript-type-string-is-not-assignable-to-type)

instead of:

```typescript
export type action_repetition = 'ONCE' | 'EVERY';
```

Which requires `'ONCE' as action_repetition` or `'ONCE' as const` casts when used in a params object, I think we should use:

```typescript
export const action_repetition = {
  ONCE: 'ONCE',
  EVERY: 'EVERY',
} as const;

export type action_repetition = keyof typeof action_repetition;
```

This allows you to use a `'ONCE'` literal and as a bonus you can import `action_repetition` and get the benefits of an enum and use the constant: `action_repetition.ONCE`.

**Comment by adelsz** [comment]
Hm, in `example/index.ts` we use `type: 'reminder'` and TS is able to infer it correctly as `const`.
It looks like by default TS infers a string as a const string literal, unless it is explicitly casted as string (like in the stackoverflow example you posted). It is a bit unergonomic, but is a reasonable requirement by the typechecker.

The double export approach proposed does look good, I would only suggest to change it to:
```ts
// generated only if enum labels are valid TS key names
// if generation not possible emit a console warning
export const enum ActionRepetitionValue {
  ONCE = 'ONCE',
  EVERY = 'EVERY',
};

// always generated
export type ActionRepetition = 'ONCE' | 'EVERY';
```
It might not always be possible to create the `ActionRepetitionValue` enum because postgres supports unicode and whitespace as enum labels.
I would also say it is safe to pascal case (haha, here I go again) the exported type/enum names.
What do you think?

**Comment by silasdavis** [comment]
> TS is able to infer it correctly as const. It looks like by default TS infers a string as a const string literal

Hm, this exactly the opposite of what I was seeing yesterday, but I cannot reproduce, how odd! I was surprised by it myself. The only think I can think of is that I had some cached types hanging around from a previous run when it was an enum.

I didn't read the stackoverflow example carefully enough, yes it's perfectly fair enough to have to narrow a string declared type.

Anyway at least I don't get to be disappointed in the typescript compiler....
