### ISSUE TITLE
Usage with concatenated query

### ISSUE THREAD

**Issue by moltar** [adelsz/pgtyped#73]
Would this library work with queries that are concatenated from parts? Any ideas on how to solve this?

Example:

```ts
let query = sql`
  SELECT *
  FROM foo
  WHERE bar = true
`

if (baz === true) {
  query += sql` AND baz = true`
}
```

Thanks!

**Comment by adelsz** [comment]
Unfortunately, PgTyped doesn't not support query concatenation.
You can still achieve the logic you describe in PgTyped and SQL using boolean ops:
```sql
SELECT * FROM foo WHERE bar = true AND (:baz != true OR baz = true);
```

**Comment by moltar** [comment]
@adelsz thanks for the tip.

My example was hypothetical, and in reality there can be many filters, which then becomes unscalable.

Thanks!
