### ISSUE TITLE
Release 0.7.1

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#75]
I see the tag exists with the enum changes, did you mean to release it or is just pending?

**Comment by adelsz** [comment]
Isn't it published? v0.7.1 is on NPM.

**Comment by silasdavis** [comment]
AH, CLI is but query isn't:

https://www.npmjs.com/package/@pgtyped/query

I guess query didn't change, I'd assumed you versioned in lockstep, but perhaps not for minor versions?

**Comment by adelsz** [comment]
Yes, by default lerna bumps and publishes only changed packages. `query` didn't change in that release.
