### ISSUE TITLE
Support other languages as plugins

### ISSUE THREAD

**Issue by user753** [adelsz/pgtyped#84]
It would be great if pgtyped could generate code in other languages through plugins similar to https://graphql-code-generator.com/docs/plugins/index

**Comment by adelsz** [comment]
Agree, I am aware of the `graphql-code-generator` plugin infrastructure and I like it a lot.
We do have some remote plans for adding generation frontends for other languages but it is a non priority at the moment, since we still have many things to do for PG+TS.
