### ISSUE TITLE
Should @pgtyped/query depend on Typescript?

### ISSUE THREAD

**Issue by silasdavis** [adelsz/pgtyped#87]
I was producing a production build with `yarn install --production` and noticed @pgtyped/query pulls in `Typescript` https://github.com/adelsz/pgtyped/blob/master/packages/query/src/index.ts#L13.

This seems odd given `query` is the runtime dependency. If it really is needed then it should be added to the `dependencies` of `@pgtyped/query` currently it's only available because it's in `devDependencies` of the root project.

It looks like the generator is the only thing that uses `parseTypescriptFile` abd `parseSQLFile`. Perhaps they should be refactored out of query?

**Comment by adelsz** [comment]
Good point, `query` is currently both a runtime and a compile-time dependency for PgTyped.

`query/loader` parsing routines are used both in the `query` package (in the preprocessor) and in the `cli` package (in generators). That is why I initially had to move loaders and parsers to `query`.

I have added TS as a peer dep for `@pgtyped/query` here #88, but we should definitely plan to split the runtime and compile-time components of it at some point.

**Comment by adelsz** [comment]
Closing, planned refactoring in #91
