### ISSUE TITLE
SSL mode

### ISSUE THREAD

**Issue by deman4ik** [adelsz/pgtyped#90]
Add config option / env variable for ssl mode.

Also option with #32 `?sslmode=require` should be enough.

**Comment by adelsz** [comment]
PgTyped is designed to run at compile-time against local DB instances, which usually do not have SSL enabled. @deman4ik Are you running a local DB with SSL on? Or you want the generated queries to be executed through SSL?

**Comment by deman4ik** [comment]
@adelsz I am using remote db instance (DaaS) for development with required ssl.

**Comment by water-a** [comment]
Are there any plans for this to be added?

Seems not that bad to add: https://github.com/brianc/node-postgres/blob/0012a43d956b1b47fc5ddf1eca5894b64f7ccf24/packages/pg/lib/connection.js

I'll take a shot at it.

**Comment by adelsz** [comment]
Thanks @water-a, I will be definitely happy to merge it.
Let me know if you run into any questions while working on that.

**Comment by water-a** [comment]
I created a pull request here: #203

**Comment by water-a** [comment]
I'm not sure how to use it from my own repo since the packages require from the npm instead of local.

**Comment by adelsz** [comment]
#203 merged, thanks again @water-a 🎉
