### ISSUE TITLE
Isolate runtime-only dependencies into their own package

### ISSUE THREAD

**Issue by adelsz** [adelsz/pgtyped#91]
It would be nice to move runtime query dependencies into a separate package.
Currently `@pgtyped/query` has both runtime and compile time logic in it.

**Comment by m-ronchi** [comment]
+1 I just found out that for some of my apps, typescipt alone is bigger that the rest of production node_modules combined, resulting in a 200MB+ docker image

any plans on this?

**Comment by gregplaysguitar** [comment]
@adelsz from investigation here it seems that typescript is no longer a dependency of @pgtyped/query, so looks like this is resolved - so I think it can be closed?

**Comment by adelsz** [comment]
This has been fixed as part of our migration to ESM.
