### ISSUE TITLE
Incompatible with other sql comments directives

### ISSUE THREAD

**Issue by darky** [adelsz/pgtyped#94]
Seems pgtyped uses strict format of sql like:

```sql
/* @name IUsers */
select * from users;
```

But something another comments breaks pgtyped:

```sql
/* bla-bla */
/* @name IUsers */
select * from users;
```

```
Parsed file:
1 |
2 > /* bla-bla */
3 > /* @name IUsers */
4 | select * from users;
5 |
Errors:
- (2:6) Parse error: token recognition error at: '-b'
- (2:3) Parse error: missing '@name' at 'bla'
- (2:8) Parse error: extraneous input 'la' expecting {'@param', '*/'}
- (3:0) Parse error: mismatched input '/*' expecting {ID, WORD, STRING}
```

In SQL can be used another comments and even directives from another tools like https://github.com/xialvjun/ts-sql-plugin, for example:

```sql
/* ts-sql-plugin:ignore-cost */
/* @name IUsers */
select * from users;
```

Need simply ignore unparsed stuff

**Comment by adelsz** [comment]
Thanks for mentioning this @darky!
This is a known bug/limitation of our parser, I will try to prioritize this.

Btw, it looks like `ts-sql-plugin` is targeting TS files not SQL files?
Not sure if `/* ts-sql-plugin:ignore-cost */` has any effect in SQL files.

**Comment by darky** [comment]
> it looks like ts-sql-plugin is targeting TS files not SQL files?

ts-sql-plugin can extract (emit) sql to explicit *.sql* files.

> Not sure if /* ts-sql-plugin:ignore-cost */ is meant to be used in SQL files.

sql files emitted as is with all comments
